"""HTML email template for Market Mover briefings."""

from datetime import datetime, timezone

from .models import RankedArticle

RANK_COLORS = {
    1: "#e74c3c",  # Red — top impact
    2: "#f39c12",  # Orange
    3: "#3498db",  # Blue
}


def render_email_html(articles: list[RankedArticle]) -> str:
    """Render top 3 ranked articles into an HTML email body.

    Args:
        articles: List of ranked articles (up to 3).

    Returns:
        Complete HTML string for the email body.
    """
    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
    article_blocks = "\n".join(_render_article_block(a) for a in articles[:3])

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1);">

<!-- Header -->
<tr>
<td style="background-color:#1a1a2e;padding:24px 32px;text-align:center;">
  <h1 style="color:#ffffff;margin:0;font-size:24px;font-weight:700;">Market Mover</h1>
  <p style="color:#a0a0b0;margin:8px 0 0;font-size:14px;">Top 3 Market-Moving Stories &mdash; {date_str}</p>
</td>
</tr>

<!-- Articles -->
<tr>
<td style="padding:24px 32px;">
{article_blocks}
</td>
</tr>

<!-- Footer -->
<tr>
<td style="background-color:#f8f8fa;padding:16px 32px;text-align:center;border-top:1px solid #eaeaea;">
  <p style="color:#888;font-size:12px;margin:0;">
    Generated by Market Mover MCP &bull; {datetime.now(timezone.utc).strftime("%I:%M %p UTC")}
  </p>
</td>
</tr>

</table>
</td></tr>
</table>
</body>
</html>"""


def render_plain_text(articles: list[RankedArticle]) -> str:
    """Render top 3 ranked articles as plain text fallback.

    Args:
        articles: List of ranked articles (up to 3).

    Returns:
        Plain text string for the email body.
    """
    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
    lines = [
        f"MARKET MOVER — Top 3 Market-Moving Stories — {date_str}",
        "=" * 60,
        "",
    ]

    for article in articles[:3]:
        action = "Watch" if article.is_video else "Read"
        lines.extend([
            f"#{article.rank} — Impact: {article.impact_score}/10",
            f"  {article.title}",
            f"  Source: {article.source_name}",
            f"  {article.market_impact_summary}",
            f"  {action}: {article.url}",
            "",
        ])

    return "\n".join(lines)


def build_subject(articles: list[RankedArticle], prefix: str = "[Market Mover]") -> str:
    """Build the email subject line from the top article.

    Args:
        articles: List of ranked articles.
        prefix: Subject prefix.

    Returns:
        Email subject string.
    """
    date_str = datetime.now(timezone.utc).strftime("%m/%d")
    if articles:
        top_title = articles[0].title[:60]
        return f"{prefix} {date_str}: {top_title}"
    return f"{prefix} {date_str}: Daily Market Briefing"


def _render_article_block(article: RankedArticle) -> str:
    """Render a single article block as HTML."""
    color = RANK_COLORS.get(article.rank, "#888888")
    action_label = "Watch" if article.is_video else "Read"
    action_icon = "&#9654;" if article.is_video else "&#8594;"

    return f"""
  <!-- Article #{article.rank} -->
  <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:20px;">
  <tr>
  <td style="padding:16px;border-left:4px solid {color};background-color:#fafafa;border-radius:0 6px 6px 0;">
    <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td>
        <span style="display:inline-block;background-color:{color};color:#fff;font-size:11px;font-weight:700;padding:2px 8px;border-radius:3px;margin-bottom:8px;">
          #{article.rank} &bull; Impact: {article.impact_score}/10
        </span>
      </td>
    </tr>
    <tr>
      <td style="padding-top:8px;">
        <a href="{article.url}" style="color:#1a1a2e;font-size:16px;font-weight:600;text-decoration:none;line-height:1.3;">
          {article.title}
        </a>
      </td>
    </tr>
    <tr>
      <td style="padding-top:4px;">
        <span style="color:#888;font-size:12px;">{article.source_name}</span>
      </td>
    </tr>
    <tr>
      <td style="padding-top:8px;">
        <p style="color:#444;font-size:14px;line-height:1.5;margin:0;">
          {article.market_impact_summary}
        </p>
      </td>
    </tr>
    <tr>
      <td style="padding-top:12px;">
        <a href="{article.url}" style="color:{color};font-size:13px;font-weight:600;text-decoration:none;">
          {action_icon} {action_label} full article
        </a>
      </td>
    </tr>
    </table>
  </td>
  </tr>
  </table>"""
