"""Pydantic models for Market Mover data structures."""

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel


class SourceType(str, Enum):
    NEWSAPI = "newsapi"
    FINNHUB = "finnhub"
    RSS = "rss"
    YOUTUBE = "youtube"


class RawArticle(BaseModel):
    """A raw article/video fetched from a news source."""

    title: str
    url: str
    source_name: str
    source_type: SourceType
    published_at: datetime | None = None
    summary: str = ""
    is_video: bool = False


class RankedArticle(BaseModel):
    """An article ranked by market impact after LLM analysis."""

    rank: int
    title: str
    url: str
    source_name: str
    market_impact_summary: str
    impact_score: float
    is_video: bool = False


class SparklineSeries(BaseModel):
    """5-day price series for one ticker, rendered as a sparkline in the email."""

    ticker: str
    close_prices: list[float]
    pct_change: float
    direction: Literal["up", "down", "flat"]


class ContrarianCoda(BaseModel):
    """A steel-manned counter-argument to today's #1 story.

    Generated by a second LLM call after the primary ranking. Rendered as
    a fourth section ("The Bear Case") at the bottom of the email.

    The ``source_url`` MUST be drawn from the pool of real articles passed
    to the generator — hallucinated URLs are rejected post-hoc and the
    coda is skipped for that day's send.
    """

    headline: str       # short, e.g. "But: 10-year yields tell a different story"
    argument: str        # 2-3 sentences max
    source_url: str      # must exist in the all_articles pool
    source_name: str     # derived from netloc downstream
